AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create MariaDB RDS instance in private subnet

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Private Subnets for RDS"
      SubnetIds:
        - subnet-09864da1583966697
        - subnet-0040409b982a72451
      DBSubnetGroupName: lks-db-subnet-group

  LKSDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for LKS RDS instance
      VpcId: vpc-0ec20d604dc3ca9e9
      SecurityGroupIngress: []  # No ingress allowed from outside
      Tags:
        - Key: Name
          Value: lks-rds-sg

  LKSDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: LKS-RDS-Apps
      Engine: mariadb
      EngineVersion: "10.6"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: admin
      MasterUserPassword: Technobrain2025!
      VPCSecurityGroups:
        - !Ref LKSDBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      BackupRetentionPeriod: 1
      DBName: techno_rds
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: LKS-RDS-Apps

Outputs:
  RDSInstanceEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt LKSDatabase.Endpoint.Address

  RDSInstanceIdentifier:
    Description: Identifier of the RDS instance
    Value: !Ref LKSDatabase
