  BucketApp:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lks-kabbanyumas-deri-25
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: deriRule
            Status: Enabled
            Transition: 
              TransitionInDays: 30
              StorageClass: GLACIER_IR
            ExpirationInDays: 365

  BucketDocker:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lks-dockerimage-deri-25
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: lks-dockerimage-deri-25
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "AllowPublicRead",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::lks-dockerimage-deri-25/*"
            }
          ]
        }